# Generated by Django 5.0.4 on 2024-04-22 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['address'], name='api_stock_address_4ab50f_idx'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='api.stock', verbose_name='Склад'),
        ),
    ]
